### PR TITLE
Don't create separate outputs for popups on Wayland

### PR DESCRIPTION
**Pull request by ilya-fedin**
Fixes https://github.com/telegramdesktop/tdesktop/issues/27427

### CODE REVIEW

**Comment by ilya-fedin** [comment]
It's not related to this PR

**Comment by tappress** [comment]
@ilya-fedin you said that this PR fixes https://github.com/telegramdesktop/tdesktop/issues/27427, so I mentioned it here

**Comment by ilya-fedin** [comment]
Yeah, that issue is fixed.

**Comment by tappress** [comment]
@ilya-fedin interesting. By the way, just wanted to ask why [CEF](https://github.com/chromiumembedded/cef) is not used on linux? Looks much more stable than WebView provided by Qt

**Comment by ilya-fedin** [comment]
Qt WebEngine is not used either. If it was used, web bots would work way better.

**Comment by ilya-fedin** [comment]
The goal (AFAIK) is to use web engine without distributing it with the app. The only library allowing that is WebKitGTK. Bugs come from embedding gtk into qt.

**Comment by tappress** [comment]
Maybe it's worth downloading the web engine dynamically when the user launches a mini app on Linux, taking into account that they went as far as installing Linux itself. Or at least this can be done when someone enables an experimental inspect feature, because it's currently impossible to develop and debug a Mini App on Linux.

**Comment by ilya-fedin** [comment]
Well, it's not me who decides

**Comment by tappress** [comment]
Whom should I address my plea?

**Comment by ilya-fedin** [comment]
@john-preston. Although he rarely reads github and I personally was telling him that the current solution won't ever work in stable manner. As far as I understand, he is ok with it.

**Comment by ilya-fedin** [comment]
Just to clear it, whatever you have is not the issue you linked. Crashes could have lots of origins and the issue you linked is Wayland-only while you say you use X11.

**Comment by tappress** [comment]
Well, I switched to Wayland and as you can see it still crashes
image

**Comment by ilya-fedin** [comment]
Still, it doesn't mean it's the issue you linked

**Comment by tappress** [comment]
Yeah, that's right

**Pull request merged**
